#!/bin/bash

#ip
frontend_server_ip=$(getent ahostsv4 frontend|  awk '{print $1}' | head -1)
public_server_ip=$(getent ahostsv4 public1|  awk '{print $1}' | head -1)
product_server_ip=$(getent ahostsv4 product |  awk '{print $1}' | head -1)
postgres_server_ip=$(getent ahostsv4 postgres |  awk '{print $1}' | head -1)

#create file of IPs
cat <<-EOF > /tmp/ticket
App Servers
  Frontend: ${frontend_server_ip}
  Public API: ${public_server_ip}
  Product API: ${product_server_ip}
  Postgres: ${postgres_server_ip}
EOF

#conf
mkdir -p /etc/nginx/conf.d
cat <<-EOF > /etc/nginx/conf.d/default.conf
# /etc/nginx/conf.d/default.conf
server {
    listen       80;
    server_name  localhost;
    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    # Proxy pass the api location to save CORS
    # Use location exposed by Consul connect
    location /api {
        proxy_pass http://127.0.0.1:8080;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
EOF

curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

cat <<-EOF > /docker-compose.yml
version: '3'
services:
  frontend:
    container_name: "frontend"
    network_mode: "host"
    image: "hashicorpdemoapp/frontend:v0.0.3"
    volumes:
       - /etc/nginx/conf.d/:/etc/nginx/conf.d/
EOF

/usr/local/bin/docker-compose up -d
