#!/bin/bash

#ip
public_server_ip=$(getent ahostsv4 public|  awk '{print $1}' | head -1)

#conf
mkdir -p /etc/nginx/conf.d
cat <<-EOF > /etc/nginx/conf.d/default.conf
# /etc/nginx/conf.d/default.conf
server {
    listen       80;
    server_name  localhost;
    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    # Proxy pass the api location to save CORS
    # Use location exposed by Consul connect
    location /api {
        proxy_pass http://${public_server_ip}:8080;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
EOF

curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

cat <<-EOF > /docker-compose.yml
version: '3'
services:
  frontend:
    network_mode: "host"
    image: "hashicorpdemoapp/frontend:v0.0.1"
    volumes:
       - /etc/nginx/conf.d/:/etc/nginx/conf.d/
EOF

/usr/local/bin/docker-compose up -d
