#!/bin/bash

cat <<-EOF > /etc/consul.d/consul-template-config.hcl
consul {
address = "localhost:8500"
retry {
  enabled = true
  attempts = 12
  backoff = "250ms"
  }
}
template {
  source      = "/etc/nginx/conf.d/default.conf.ctmpl"
  destination = "/etc/nginx/conf.d/default.conf"
  perms = 0600
  command = "docker exec frontend nginx -s reload"
}
EOF

nohup consul-template --log-level=debug -config=/etc/consul.d/consul-template-config.hcl > /consul-template.out &

sleep 5
