#!/bin/bash

cat <<-EOF > /etc/nginx/conf.d/default.conf.ctmpl
upstream backend {
{{ range service "public" }}
  server {{ .Address }}:{{ .Port }};
{{ end }}
}
server {
    listen       80;
    server_name  localhost;
    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    # Proxy pass the api location to save CORS
    # Use location exposed by Consul connect
    location /api {
        proxy_pass http://backend;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
EOF

cat <<-EOF > /etc/consul.d/consul-template-config.hcl
consul {
address = "localhost:8500"
retry {
  enabled = true
  attempts = 12
  backoff = "250ms"
  }
}
template {
  source      = "/etc/nginx/conf.d/default.conf.ctmpl"
  destination = "/etc/nginx/conf.d/default.conf"
  perms = 0600
  command = "docker exec frontend nginx -s reload"
}
EOF

nohup consul-template --log-level=debug -config=/etc/consul.d/consul-template-config.hcl > /consul-template.out &

sleep 5
