#!/bin/bash

service consul stop
local_ipv4=$(curl -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/ip)

#consul
mkdir -p /consul/data

cat <<-EOF > /etc/consul.d/client.json
{
  "datacenter": "dc1",
  "server": false,
  "bind_addr": "${local_ipv4}",
  "client_addr": "0.0.0.0",
  "data_dir": "/consul/data",
  "log_level": "INFO",
  "node_name": "Product",
  "retry_join": [
    "consul:8301"
  ]
}
EOF

cat <<-EOF > /etc/consul.d/product-service.json
{
  "service": {
    "name": "product",
    "port": 9090,
    "tags": ["api"],
    "check": {
      "id": "api",
      "name": "api TCP on port 9090",
      "tcp": "localhost:9090",
      "interval": "3s",
      "timeout": "1s"
    }
  }
}
EOF

service consul start
